// File generated by FlutterFire CLI.
// 실제 파일은 'flutterfire configure' 명령어로 생성해야 합니다.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// 기본 Firebase 설정 옵션 클래스
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 실제 사용 시에는 Firebase 콘솔에서 앱을 등록하고 flutterfire CLI를 사용하여
  // 실제 키값들을 가져와야 합니다.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGSrPpW-k8nygvLoq6S9lC-X9XvmwL1Y',
    appId: '1:154555120691:web:334ab06835855667f83746',
    messagingSenderId: '154555120691',
    projectId: 'pulse-d9a3a',
    authDomain: 'pulse-d9a3a.firebaseapp.com',
    storageBucket: 'pulse-d9a3a.firebasestorage.app',
    measurementId: 'G-68K6G3BGTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBxARALoN5CcH6Etl8ukdOnyF1MHhi5w',
    appId: '1:154555120691:android:c383dd8d47819cdaf83746',
    messagingSenderId: '154555120691',
    projectId: 'pulse-d9a3a',
    storageBucket: 'pulse-d9a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUaQL4ySXVK-NEX5OoPfnkPLx-7BmCMlk',
    appId: '1:154555120691:ios:5ec0861809745aa3f83746',
    messagingSenderId: '154555120691',
    projectId: 'pulse-d9a3a',
    storageBucket: 'pulse-d9a3a.firebasestorage.app',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'YOUR-MACOS-BUNDLE-ID',
  );
}